spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # To run the application, replace this with a valid JWK Set URI
          jwk-set-uri: https://example.com/oauth2/default/v1/keys
